require("settings.settings")
require("settings.remaps")
require("settings.plugins")
require("settings.telescope-maps")
require("settings.tree_sitter")
require("settings.harpoon")
require("settings.undotree")
require("settings.fugitive")
require("settings.lsp")
require("settings.nvim_webicons")
require("settings.lua_line")

